apiVersion: v2
name: openstack-cinder
description: OpenStack Cinder Block Storage Service
type: application
version: 0.1.0
appVersion: "2025.1"

dependencies:
  - name: cinder
    version: "2025.2.7+aed8f5826"
    repository: "https://tarballs.opendev.org/openstack/openstack-helm/"
