apiVersion: v2
name: openstack-placement
description: OpenStack Placement Service - Resource tracking and inventory
type: application
version: 0.1.0
appVersion: "2025.1"

dependencies:
  - name: placement
    version: "2025.2.5+01c93d867"
    repository: "https://tarballs.opendev.org/openstack/openstack-helm/"
