apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ceph-etc-configmap.yaml
  - cinder-rbd-keyring-secret.yaml
  - glance-rbd-keyring-secret.yaml
  - nova-rbd-keyring-secret.yaml
