#!/bin/bash
# Set up OVS external bridge for provider network (reboot-safe)
# Run as root on the compute node: sudo bash 05-setup-ovs-bridge.sh
#
# This script:
#   1. Creates br-ex as an OVS bridge
#   2. Adds the physical interface (eno1) as an OVS port
#   3. Migrates the management IP from the physical interface to br-ex
#   4. Writes a persistent netplan config so this survives reboots
#
# After reboot, netplan + OVS handle everything automatically:
#   - openvswitch-switch starts and loads bridge config from ovsdb
#   - netplan assigns the management IP to br-ex
#   - eno1 is enslaved to br-ex via bridges.br-ex.interfaces
#   - VLAN-tagged traffic (e.g., VLAN 60 for provider network) flows through br-ex

set -euo pipefail

# === CONFIGURATION ===
PHYSICAL_INTERFACE="${1:-eno1}"   # Physical NIC (pass as arg or defaults to eno1)
MANAGEMENT_IP="${2:-}"           # e.g., 192.168.30.13/24 (auto-detected if empty)
GATEWAY="${3:-}"                 # e.g., 192.168.30.1 (auto-detected if empty)
DNS_SERVERS="${4:-192.168.10.1}" # DNS servers (comma-separated)
APPLY_NETPLAN="${APPLY_NETPLAN:-true}" # Set to false to only render config
# =====================

echo "=== OVS External Bridge Setup (reboot-safe) ==="
echo ""

# Auto-detect IP and gateway if not provided
if [ -z "$MANAGEMENT_IP" ]; then
    MANAGEMENT_IP=$(ip addr show ${PHYSICAL_INTERFACE} | grep 'inet ' | awk '{print $2}' | head -1)
    if [ -z "$MANAGEMENT_IP" ]; then
        # Maybe IP is already on br-ex (re-running script)
        MANAGEMENT_IP=$(ip addr show br-ex 2>/dev/null | grep 'inet ' | awk '{print $2}' | head -1)
    fi
fi

if [ -z "$GATEWAY" ]; then
    GATEWAY=$(ip route | grep default | awk '{print $3}' | head -1)
fi

if [ -z "$MANAGEMENT_IP" ] || [ -z "$GATEWAY" ]; then
    echo "ERROR: Could not detect management IP or gateway."
    echo "Usage: $0 <interface> <ip/mask> <gateway> [dns]"
    echo "Example: $0 eno1 192.168.30.13/24 192.168.30.1"
    exit 1
fi

echo "Physical interface: ${PHYSICAL_INTERFACE}"
echo "Management IP:      ${MANAGEMENT_IP}"
echo "Default gateway:    ${GATEWAY}"
echo "DNS servers:        ${DNS_SERVERS}"
echo ""

# Ensure OVS is running
command -v ovs-vsctl >/dev/null 2>&1 || {
    echo "ERROR: ovs-vsctl not found. Install openvswitch-switch first."
    exit 1
}
systemctl enable openvswitch-switch >/dev/null 2>&1 || true
systemctl restart openvswitch-switch

# Step 1: Create br-ex and add the physical interface
echo ">>> Creating OVS bridge br-ex with port ${PHYSICAL_INTERFACE}..."
ovs-vsctl --may-exist add-br br-ex
ovs-vsctl --may-exist add-port br-ex ${PHYSICAL_INTERFACE}
if ! ovs-vsctl list-ports br-ex | grep -qx "${PHYSICAL_INTERFACE}"; then
    echo "ERROR: ${PHYSICAL_INTERFACE} is not attached to br-ex."
    exit 1
fi

# Step 2: Migrate IP to br-ex (runtime — immediate effect)
echo ">>> Migrating IP to br-ex..."
ip addr del ${MANAGEMENT_IP} dev ${PHYSICAL_INTERFACE} 2>/dev/null || true
ip addr add ${MANAGEMENT_IP} dev br-ex 2>/dev/null || true
ip link set br-ex up
ip route replace default via ${GATEWAY} dev br-ex 2>/dev/null || true

# Step 3: Write persistent netplan config
echo ">>> Writing persistent netplan config..."

# Back up any existing netplan configs that configure eno1
for f in /etc/netplan/*.yaml; do
    if grep -q "${PHYSICAL_INTERFACE}" "$f" 2>/dev/null; then
        if [ "$f" != "/etc/netplan/60-ovs-bridge.yaml" ]; then
            echo "    Backing up $f -> ${f}.bak"
            cp "$f" "${f}.bak"
            # Comment out the old config to prevent conflicts
            mv "$f" "${f}.disabled"
        fi
    fi
done

cat <<EOF > /etc/netplan/60-ovs-bridge.yaml
# OVS external bridge for OpenStack provider network
# Generated by 05-setup-ovs-bridge.sh — do not edit manually
# To regenerate: sudo bash 05-setup-ovs-bridge.sh ${PHYSICAL_INTERFACE} ${MANAGEMENT_IP} ${GATEWAY}
network:
  version: 2
  renderer: networkd
  ethernets:
    ${PHYSICAL_INTERFACE}:
      dhcp4: false
      dhcp6: false
  bridges:
    br-ex:
      interfaces: [${PHYSICAL_INTERFACE}]
      openvswitch: {}
      addresses:
        - ${MANAGEMENT_IP}
      routes:
        - to: default
          via: ${GATEWAY}
      nameservers:
        addresses: [${DNS_SERVERS}]
EOF

chmod 600 /etc/netplan/60-ovs-bridge.yaml

echo ">>> Generating netplan..."
netplan generate

if [ "${APPLY_NETPLAN}" = "true" ]; then
    echo ">>> Applying netplan..."
    netplan apply
else
    echo ">>> Skipping netplan apply (APPLY_NETPLAN=${APPLY_NETPLAN})"
fi

echo ""
echo "=== Setup Complete ==="
echo ""
echo "Current OVS bridge config:"
ovs-vsctl show | head -30
echo ""
echo "Current IP on br-ex:"
ip addr show br-ex | grep 'inet '
echo ""
echo "Open vSwitch service:"
systemctl --no-pager --full status openvswitch-switch | sed -n '1,5p'
echo ""
echo "Netplan config written to: /etc/netplan/60-ovs-bridge.yaml"
echo ""
echo "To verify after reboot:"
echo "  ip addr show br-ex       # Should have ${MANAGEMENT_IP}"
echo "  ovs-vsctl list-ports br-ex  # Should show ${PHYSICAL_INTERFACE}"
echo "  ping ${GATEWAY}          # Should work"
